# Generated by Django 5.2.7 on 2025-11-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimPeriodo',
            fields=[
                ('id_periodo', models.IntegerField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField()),
            ],
            options={
                'db_table': 'cesfam_core"."dim_periodo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArchivoREM',
            fields=[
                ('id_archivo', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_original', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='rem_uploads/')),
                ('tipo_rem', models.CharField(blank=True, max_length=10, null=True)),
                ('periodo', models.CharField(blank=True, max_length=7, null=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('procesado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'archivo_rem',
            },
        ),
    ]
