# Generated by Django 5.2.7 on 2025-11-17 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroREM',
            fields=[
                ('id_registro', models.BigAutoField(primary_key=True, serialize=False)),
                ('hoja', models.CharField(max_length=10)),
                ('seccion', models.CharField(max_length=10)),
                ('fila', models.IntegerField(default=0)),
                ('datos', models.JSONField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='rem.archivorem')),
            ],
            options={
                'db_table': 'registro_rem',
            },
        ),
    ]
