# Generated by Django 5.2.7 on 2025-11-26 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0002_registrorem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivorem',
            name='tipo_rem',
        ),
        migrations.AlterField(
            model_name='archivorem',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos', to='rem.dimperiodo'),
        ),
        migrations.AlterField(
            model_name='registrorem',
            name='seccion',
            field=models.CharField(max_length=20),
        ),
    ]
