# Generated by Django 5.2.7 on 2025-11-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rem', '0003_remove_archivorem_tipo_rem_alter_archivorem_periodo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivorem',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
